# Generated by Django 3.1.7 on 2021-04-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateEstablished', models.DateField()),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('domain', models.CharField(choices=[('Technology', 'Technology'), ('Education', 'Education'), ('Environment', 'Environment'), ('Humanities', 'Humanities'), ('Arts', 'Arts'), ('Business', 'Business'), ('Politics', 'Politics')], default='Education', max_length=50)),
                ('orgHead', models.CharField(max_length=25)),
                ('numMembers', models.PositiveIntegerField()),
            ],
        ),
    ]
